### ISSUE TITLE
as a user I would like to start my status from a template

### ISSUE THREAD

**Issue by ds0001** [huynhquancam/worque#12]

**Comment by qcam** [comment]
Can you be more specific?

**Comment by ds0001** [comment]
@huynhquancam so I was thinking something along the lines of a custom base template for each days status document. something like...

```
Status for {date}

*Todo: Most Important*

*Todo: Nice To Have*

```

**Comment by ds0001** [comment]
So my use case is to use `worque` as a list of things I need to do. Not necessarily as a list of things I've already done.

**Comment by ds0001** [comment]
but I can see this useful for other use cases. example:

```
Status for {date}

*Tasks Done*

*Tasks Pending*
```

**Comment by qcam** [comment]
Interesting idea.  By default, we can load the file located at `~/worque.template`

**Comment by ds0001** [comment]
that would be awesome

**Comment by qcam** [comment]
Would you like to take this? cc @ds0001

**Comment by ds0001** [comment]
@huynhquancam sure

**Comment by qcam** [comment]
Fixed via https://github.com/qcam/worque/commit/363493198b9a5faa21f85587ec5af1b1a498aee4
